"""Update House fields

Revision ID: 0461e6a1713b
Revises: 4584d0ed01e0
Create Date: 2026-02-24 13:25:02.139856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '0461e6a1713b'
down_revision: Union[str, Sequence[str], None] = '4584d0ed01e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('houses', 'description',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("''"),
               existing_nullable=False)
    op.alter_column('houses', 'price',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('houses', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('FALSE'),
               existing_nullable=False)
    op.alter_column('houses', 'rooms',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               nullable=False)
    op.alter_column('houses', 'bathrooms',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('houses', 'bathrooms',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('houses', 'rooms',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('houses', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('houses', 'price',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('houses', 'description',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
