"""Added new fields to House

Revision ID: 1363b9e94350
Revises: 0461e6a1713b
Create Date: 2026-02-24 13:29:50.072570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1363b9e94350'
down_revision: Union[str, Sequence[str], None] = '0461e6a1713b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('text', sa.TEXT(), server_default=sa.text("''"), nullable=False))
    op.add_column('houses', sa.Column('quality_score', sa.FLOAT(), server_default=sa.text('0'), nullable=False))
    op.add_column('houses', sa.Column('deposit', sa.Integer(), nullable=True))
    op.add_column('houses', sa.Column('pets_allowed', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_houses_quality_score'), 'houses', ['quality_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_houses_quality_score'), table_name='houses')
    op.drop_column('houses', 'pets_allowed')
    op.drop_column('houses', 'deposit')
    op.drop_column('houses', 'quality_score')
    op.drop_column('houses', 'text')
    # ### end Alembic commands ###
