"""update house columns

Revision ID: 4584d0ed01e0
Revises: 505ed3046ef5
Create Date: 2026-02-19 17:42:38.324364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '4584d0ed01e0'
down_revision: Union[str, Sequence[str], None] = '505ed3046ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('square', sa.Integer(), nullable=True))
    op.add_column('houses', sa.Column('rooms', sa.Integer(), nullable=True))
    op.add_column('houses', sa.Column('bathrooms', sa.Integer(), nullable=True))
    op.add_column('houses', sa.Column('free_parking', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('houses', 'free_parking')
    op.drop_column('houses', 'bathrooms')
    op.drop_column('houses', 'rooms')
    op.drop_column('houses', 'square')
    # ### end Alembic commands ###
