"""create initial tables

Revision ID: 505ed3046ef5
Revises: 
Create Date: 2026-02-19 17:33:16.609907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '505ed3046ef5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_houses_active'), 'houses', ['active'], unique=False)
    op.create_index(op.f('ix_houses_name'), 'houses', ['name'], unique=False)
    op.create_index(op.f('ix_houses_price'), 'houses', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_houses_price'), table_name='houses')
    op.drop_index(op.f('ix_houses_name'), table_name='houses')
    op.drop_index(op.f('ix_houses_active'), table_name='houses')
    op.drop_table('houses')
    # ### end Alembic commands ###
